function accounting(){const m=metrics(),balances={};state.journals.forEach(j=>j.rows.forEach(r=>balances[r.account]=(balances[r.account]||0)+(r.debit||0)-(r.credit||0)));return `<div class="pageGrid"><div class="stats4">${stat('Sales Net',money(m.salesGross-m.vat),'Credit revenue')}${stat('Output VAT',money(m.vat),'VAT payable')}${stat('COGS',money(m.cogs),'Cost of sales')}${stat('Journals',state.journals.length,'Auto-posted')}</div><div class="twoCol"><div class="panel">${panelTitle('Trial Balance','LIVE')}<table><thead><tr><th>Account</th><th class="num">Debit</th><th class="num">Credit</th></tr></thead><tbody>${Object.entries(balances).sort().map(([a,b])=>`<tr><td>${esc(a)}</td><td class="num">${b>0?money(b):'—'}</td><td class="num">${b<0?money(-b):'—'}</td></tr>`).join('')}</tbody></table></div><div class="panel">${panelTitle('Journal Entries',`${state.journals.length} entries`)}${state.journals.length?`<div class="journalList">${state.journals.slice(0,12).map(j=>`<details><summary><div><b>${esc(j.source)}</b><span>${esc(j.description)}</span></div><small>${new Date(j.date).toLocaleString('en-AE')}</small></summary>${j.rows.map(r=>`<div class="jr"><span>${esc(r.account)}</span><span>${r.debit?`Dr ${money(r.debit)}`:`Cr ${money(r.credit)}`}</span></div>`).join('')}</details>`).join('')}</div>`:empty('Journal entries will appear automatically after transactions.')}</div></div></div>`}

function reports(){const m=metrics(),methods={},top={};state.sales.forEach(s=>{methods[s.paymentMethod]=(methods[s.paymentMethod]||0)+s.total;s.items.forEach(i=>top[i.name]=(top[i.name]||0)+i.qty)});return `<div class="pageGrid"><div class="stats4">${stat('Revenue ex VAT',money(m.salesGross-m.vat))}${stat('Gross Profit',money(m.grossProfit))}${stat('Expenses',money(m.expenses))}${stat('Estimated Result',money(m.netAfterExpenses))}</div><div class="twoCol"><div class="panel">${panelTitle('Payment Summary')}${Object.keys(methods).length?Object.entries(methods).map(([k,v])=>`<div class="progressRow"><span>${esc(k)}</span><b>${money(v)}</b></div>`).join(''):empty('No payment data yet.')}</div><div class="panel">${panelTitle('Top Items')}${Object.keys(top).length?Object.entries(top).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([k,v])=>`<div class="progressRow"><span>${esc(k)}</span><b>${v} sold</b></div>`).join(''):empty('No sales data yet.')}</div></div></div>`}

function settings(){return `<div class="twoCol"><form class="panel form" id="settingsForm"><h3>Business Settings</h3><label>Legal / Trade Name<input name="name" value="${escAttr(state.business.name)}"></label><label>TRN<input name="trn" value="${escAttr(state.business.trn)}"></label><label>Branch<input name="branch" value="${escAttr(state.business.branch)}"></label><label>VAT Rate<input value="5%" disabled></label><button class="primary">Save Settings</button></form><div class="panel pad"><h3>System</h3><p class="muted">This MVP stores data locally in this browser. Production will use secure multi-tenant cloud storage, authentication, branch permissions and real integrations.</p><button class="danger" id="resetDemo">Reset Demo Data</button></div></div>`}

function paymentModal(){const t=cartTotals();return `<div class="overlay" id="paymentOverlay"><div class="modal"><button class="x" data-close-payment>×</button><span class="eyebrow">AMOUNT DUE</span><h2>${money(t.total)}</h2><p>Select payment method</p><div class="payMethods"><button data-pay="Cash">Cash</button><button data-pay="Card">Card</button><button data-pay="Other">Bank / Other</button></div></div></div>`}
function receiptModal(sale){const c=state.customers.find(x=>x.id===sale.customerId);return `<div class="overlay"><div class="modal receipt"><button class="x noPrint" id="closeReceipt">×</button><div class="receiptHead"><b>${esc(state.business.name)}</b><span>${esc(state.business.branch)}</span><span>TRN ${esc(state.business.trn)}</span><h3>TAX INVOICE</h3><small>${sale.id} · ${new Date(sale.createdAt).toLocaleString('en-AE')}</small></div>${c?`<div class="receiptCustomer"><span>Customer</span><b>${esc(c.name)}</b>${c.trn?`<small>TRN ${esc(c.trn)}</small>`:''}</div>`:''}<div class="receiptLines">${sale.items.map(i=>`<div><span>${i.qty} × ${esc(i.name)}</span><b>${money(i.price*i.qty)}</b></div>`).join('')}</div><div class="receiptTotals"><div><span>Net</span><b>${money(sale.net)}</b></div><div><span>VAT 5%</span><b>${money(sale.vat)}</b></div><div class="grand"><span>Total</span><b>${money(sale.total)}</b></div><div><span>Paid via</span><b>${esc(sale.paymentMethod)}</b></div></div><button class="primary full noPrint" id="printReceipt">Print Receipt</button></div></div>`}

function bindCommon(){document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{ui.page=b.dataset.nav;render()});document.querySelector('#newSale').onclick=()=>{ui.page='Sell';render()};const close=document.querySelector('#closeReceipt');if(close)close.onclick=()=>{ui.receipt=null;render()};const print=document.querySelector('#printReceipt');if(print)print.onclick=()=>window.print();}
function bindPage(){
  if(ui.page==='Sell'){
    const search=document.querySelector('#search');search.oninput=e=>{ui.search=e.target.value;render()};
    document.querySelectorAll('[data-product]').forEach(b=>b.onclick=()=>addToCart(b.dataset.product));
    document.querySelectorAll('[data-qty]').forEach(b=>b.onclick=()=>changeQty(b.dataset.qty,+b.dataset.d));
    document.querySelector('#customerSel').onchange=e=>ui.customerId=e.target.value;
    document.querySelector('#payBtn').onclick=openPayment;
  }
  if(ui.page==='Products') document.querySelector('#productForm').onsubmit=addProduct;
  if(ui.page==='Customers') document.querySelector('#customerForm').onsubmit=addCustomer;
  if(ui.page==='Expenses') document.querySelector('#expenseForm').onsubmit=addExpense;
  if(ui.page==='Settings'){
    document.querySelector('#settingsForm').onsubmit=saveSettings;
    document.querySelector('#resetDemo').onclick=()=>{if(confirm('Reset all demo data?')){state=structuredClone(seed);ui.cart=[];save();render();toast('Demo data reset')}};
  }
}
function addToCart(id){const p=state.products.find(x=>x.id===id);if(!p)return;if(!p.nonStock&&p.stock<=0)return toast('Out of stock');const f=ui.cart.find(x=>x.id===id);if(f){if(!p.nonStock&&f.qty>=p.stock)return toast('No more stock available');f.qty++}else ui.cart.push({...p,qty:1});render()}
function changeQty(id,d){const x=ui.cart.find(x=>x.id===id);if(!x)return;const p=state.products.find(p=>p.id===id);if(d>0&&!p.nonStock&&x.qty>=p.stock)return toast('No more stock available');x.qty+=d;if(x.qty<=0)ui.cart=ui.cart.filter(i=>i.id!==id);render()}
function openPayment(){if(!ui.cart.length)return;document.body.insertAdjacentHTML('beforeend',paymentModal());document.querySelector('[data-close-payment]').onclick=()=>document.querySelector('#paymentOverlay').remove();document.querySelectorAll('[data-pay]').forEach(b=>b.onclick=()=>completeSale(b.dataset.pay));}
function completeSale(method){const t=cartTotals(),sale={id:`INV-${String(state.sales.length+1).padStart(5,'0')}`,createdAt:now(),customerId:ui.customerId,items:ui.cart.map(x=>({id:x.id,name:x.name,qty:x.qty,price:x.price,cost:x.cost})),net:t.net,vat:t.vat,total:t.total,cogs:t.cogs,paymentMethod:method};const payAccount=method==='Cash'?'Cash on Hand':method==='Card'?'Card Clearing':'Bank / Other Clearing';const journal={id:`JE-${uid()}`,date:sale.createdAt,source:sale.id,description:`POS Sale ${sale.id}`,rows:[{account:payAccount,debit:sale.total,credit:0},{account:'Sales Revenue',debit:0,credit:sale.net},{account:'VAT Output Payable',debit:0,credit:sale.vat},{account:'Cost of Goods Sold',debit:sale.cogs,credit:0},{account:'Inventory',debit:0,credit:sale.cogs}]};state={...state,sales:[sale,...state.sales],products:state.products.map(p=>{const c=ui.cart.find(x=>x.id===p.id);return c&&!p.nonStock?{...p,stock:Math.max(0,p.stock-c.qty)}:p}),journals:[journal,...state.journals]};ui.cart=[];ui.receipt=sale;save();document.querySelector('#paymentOverlay')?.remove();render();toast(`${sale.id} completed`)}
function addProduct(e){e.preventDefault();const f=new FormData(e.target),name=f.get('name'),price=+f.get('price');if(!name||!price)return;const p={id:`P-${uid()}`,name,sku:f.get('sku')||uid(),category:f.get('category')||'Retail',price,cost:+f.get('cost')||0,stock:+f.get('stock')||0,lowStock:5};setState(s=>({...s,products:[p,...s.products]}));toast('Product added')}
function addCustomer(e){e.preventDefault();const f=new FormData(e.target),name=f.get('name');if(!name)return;setState(s=>({...s,customers:[...s.customers,{id:`C-${uid()}`,name,phone:f.get('phone')||'',trn:f.get('trn')||''}]}));toast('Customer added')}
function addExpense(e){e.preventDefault();const f=new FormData(e.target),amount=+f.get('amount'),description=f.get('description');if(!description||!amount)return;const ex={id:`EXP-${uid()}`,createdAt:now(),description,category:f.get('category'),amount,paymentMethod:f.get('paymentMethod')},account=ex.paymentMethod==='Cash'?'Cash on Hand':'Bank / Card';const j={id:`JE-${uid()}`,date:ex.createdAt,source:ex.id,description:ex.description,rows:[{account:`Expense - ${ex.category}`,debit:amount,credit:0},{account,debit:0,credit:amount}]};setState(s=>({...s,expenses:[ex,...s.expenses],journals:[j,...s.journals]}));toast('Expense posted')}
function saveSettings(e){e.preventDefault();const f=new FormData(e.target);setState(s=>({...s,business:{name:f.get('name'),trn:f.get('trn'),branch:f.get('branch')}}));toast('Business settings saved')}
function esc(v=''){return String(v).replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}function escAttr(v=''){return esc(v).replace(/'/g,'&#39;')}
render();
